Add go version from go.mod in GH Workflow
sustainable-computing-io/kepler-operator pull request #107
Opened 2023-07-24 17:09 UTC by husky-parul

- Fixes #101  https://github.com/sustainable-computing-io/kepler-operator/issues/101
Signed-off-by: Parul Singh <parsingh@redhat.com>

2023-07-24 23:40 UTC, sthaha commented on sm.yaml
> +
Was this added by mistake ?

2023-07-24 23:40 UTC, sthaha requested changes
Could you please resubmit with the unrelated file removed :) ?

2023-07-27 01:17 UTC, husky-parul commented
@sthaha Please TAL

2023-07-27 01:46 UTC, sthaha approved these changes
/lgtm

2023-07-27 01:47 UTC, merged