fix make bundle
sustainable-computing-io/kepler-operator pull request #129
Opened 2023-08-08 19:13 UTC by vprashar2929

This PR:
1. adds support to make yq part of make tools.
2. change the directory from config/manager to config/manifests while setting the image controller.
3. move the bundle.Dockerfile to bundles dir post generating bundle.

2023-08-08 22:42 UTC, sthaha commented on Makefile
>  	sed < bundle/manifests/kepler-operator.clusterserviceversion.yaml "s|containerImage.*|containerImage: $(OPERATOR_IMG)|g" \
is this needed? doesn't the `set image controller` above not work?

2023-08-08 22:44 UTC, sthaha commented on config/manifests/kustomization.yaml
> -#      path: /spec/template/spec/volumes/0
Could you please maintain this? We will need webhooks soon to disallow creation of kepler instances other than kepler.

2023-08-08 22:46 UTC, sthaha requested changes
This commit does 3 things. We should break that in to 3 commits. 
1. patch that installs yq
2. fix the bundle
3. remove webhook part that is commented. 

Why is this important? 
lets say we want to revert the `fix bundle part` or `remove webhook` part, `git revert <commit>` is all that is needed. You can make 3 different commits from the same file using `git add -p` to select parts that form part of the commit. 


Do note the main reason for holding this PR is to make sure that we need / do not need the `sed`

2023-08-09 08:52 UTC, vprashar2929 reviewed
LGTM

2023-08-09 08:53 UTC, sthaha approved these changes

2023-08-09 08:53 UTC, merged