feat(dashboard): enhance OpenShift dashboard
sustainable-computing-io/kepler-operator pull request #247
Opened 2023-09-25 13:10 UTC by jgbernalp

Fixes: #246

https://issues.redhat.com/browse/OU-250

https://github.com/sustainable-computing-io/kepler-operator/assets/5461414/21c52a33-f013-4b65-be62-95e0d2f6b3a1

2023-09-25 13:29 UTC, vprashar2929 commented
Quick question can we add units to the panel value like Watt or Killowatt? For eg. In the case of `Total Energy Consumption` panel  the value we get is in Killowatt-hour

2023-09-25 14:46 UTC, jgbernalp commented
@vprashar2929 yes, I added the units in the total energy consumption panel. Unfortunately other panels, like tables and line charts are limited on that

2023-09-25 14:59 UTC, jgbernalp commented
![Screenshot 2023-09-25 at 16 47 06](https://github.com/sustainable-computing-io/kepler-operator/assets/5461414/e239bdc5-cd12-4015-821e-f56a5893c444)

2023-09-25 15:11 UTC, vimalk78 commented
@jgbernalp can we sort the top10 namespace table by values?

2023-09-25 16:54 UTC, jgbernalp commented
@vprashar2929 yes makes sense, i've moved them.

2023-09-27 07:57 UTC, fkargbo commented
With regards to Phase 1 of this initiative, looks good to me. Thanks!

2023-09-28 18:47 UTC, vprashar2929 commented
Just one comment about moving `Total Power Consumption (W) in Namespace` and `Total Power Consumption (kWh per day) in Namespace` panels to the top in `kepler-dashboard-namespace.json`

2023-09-28 22:15 UTC, sthaha commented on pkg/components/exporter/assets/kepler-dashboard-namespace.json
@jgbernalp could you please rename the file to `powermon-dashboard-namespace.json`

2023-09-28 22:18 UTC, sthaha commented on pkg/components/exporter/assets/kepler-dashboard-overview.json
@jgbernalp,
For the PR to pass CI,  we need to rename this to `powermon-dashboard-overview.json` and also update the 
https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/pkg/components/exporter/exporter.go#L87 to use this file. 

I will then create a follow-up PR that deploys both dashboards.

2023-09-28 22:19 UTC, sthaha requested changes
The https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/pkg/components/exporter/exporter.go#L87 needs correction.

2023-09-29 07:49 UTC, closed without merging

2023-09-29 07:49 UTC, jgbernalp commented
Changes were included by #258