Updated Bundle
sustainable-computing-io/kepler-operator pull request #43
Opened 2023-01-26 18:39 UTC by KaiyiLiu1234

Bundle has been updated with most up to date docker image. Once this PR is approved, the kepler operator v0.4 should be completed. Note that the Operator sdk version in the bundle went from 1.25 to 1.23 after updating the bundle. Will this be an issue?

2023-01-27 17:35 UTC, KaiyiLiu1234 commented
I just copy and pasted the icon into clusterserviceversion.yaml in bundle and config manifest. Not sure if there was a programatic way of doing it.

2023-01-27 18:51 UTC, KaiyiLiu1234 commented
@husky-parul I noticed that github actions are still failing because of the username password missing. Is there anything that can be done to resolve that?

2023-01-31 17:43 UTC, husky-parul commented
![image](https://user-images.githubusercontent.com/24639524/215839468-d65cb4af-78c5-41c6-8477-6ca52aa0cce3.png)

- Add repository name
- Add CREATED AT
- Add channel as `v1alpha1`
- Add quay.io image link under container image
- Add https://github.com/sustainable-computing-io/kepler-operator in created at
- Need Introduction, Documentation, Contributing and License information. Follow sample csv here https://operatorhub.io/operator/openshift-qiskit-operator

You can preivew the csv here https://operatorhub.io/preview

2023-01-31 17:44 UTC, husky-parul requested changes
I have added some comments.

2023-01-31 17:50 UTC, husky-parul commented
> @husky-parul I noticed that github actions are still failing because of the username password missing. Is there anything that can be done to resolve that?

The checks have passed. Once the PR is merged the workflow will build and push the image.

2023-01-31 22:07 UTC, husky-parul commented on config/manifests/bases/kepler-operator.clusterserviceversion.yaml
>      name: https://sustainable-computing.io/
Name is string. Use "Kepler Operator Contributors" That is why the link is not rendering.

2023-01-31 22:13 UTC, husky-parul approved these changes
LGTM

2023-01-31 22:22 UTC, merged